### ISSUE TITLE
TypeError: can't pickle thread.lock objects

### ISSUE THREAD

**Issue by rtayne** [toutils/todbmanager#2]
Getting Errors on Windows 10 Pro:
login success!
config: enter for (default)
auto-update: will stop update when no new data on a page
auto-update (y)/n:
page start(1):
page end:0 = all pages (default)
page end(0):
rate limit(2.0) in seconds:
2019-02-12 09:51:01.485000:info:scrape_to:scrape started

scrape_to:auto updating page_end
scrape_to:auto update enabled
scarpe_to:setting orderby to edit
scraping pages:1-15031
rate limit,waiting:1.9849998951
requesting:reports?page=1
launching process for:reports?page=1
Traceback (most recent call last):
  File "todbmanager.py", line 817, in <module>
    main()
  File "todbmanager.py", line 741, in main
    scrape_to(to_api,page_start,page_end,rate_limit,auto_update)
  File "todbmanager.py", line 467, in scrape_to
    scrape_process.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 568, in save_tuple
    save(element)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 731, in save_inst
    save(stuff)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 401, in save_reduce
    save(args)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 554, in save_tuple
    save(element)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 606, in save_list
    self._batch_appends(iter(obj))
  File "C:\Python27\lib\pickle.py", line 639, in _batch_appends
    save(x)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 731, in save_inst
    save(stuff)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 731, in save_inst
    save(stuff)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 306, in save
    rv = reduce(self.proto)
TypeError: can't pickle thread.lock objects

> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)
  File "C:\Python27\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "C:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 886, in load_eof
    raise EOFError
EOFError

**Comment by toutils** [comment]
I was able to replicate this on windows 7 but I haven't been able to immediately fix it. This is going to have to be dealt with when the code is cleaned up / rewritten. I'm probably going to drop this multiprocessing altogether since it isn't being used for much; I don't plan on setting this up to hammer TO with requests.

**Comment by toutils** [comment]
Specifically this is this issue
https://docs.python.org/2/library/multiprocessing.html#windows
what's being sent to Process.__init__() is not pickleable

scrape_process=Process(target=worker,args=(to_api,reports_page,request_url,queue))

queue is not pickleable, instead of using multiprocessing.queue you can use multiprocessing.manager.queue, which is, but that doesn't solve the problem, because to_api is not pickleable. 

Really this whole thing needs to be simplified. There's already a workaround in to_api to deal with multiprocessing involving blocked userids, I don't want to pile more junk on junk.

**Comment by rtayne** [comment]
Ok very good, I found the same python doc you did but didn't look into it any further.

Thank you for your for doing this!

**Comment by toutils** [comment]
I just pushed v0.3, which shouldn't have this problem. I tested it in windows 7 and it seemed to run fine. I removed multiprocessing all together, but in the future if it's re-added it shouldn't have this pickle problem, or if it does it should be much easier to fix. I'll keep this open until I add v0.3 to the release tab along with the database, I'm still testing it and generating the new database.

**Comment by rtayne** [comment]
I should have read this more carefully.  Lol! I just realized, today I was trying to make V0.2 run on python3!

**Comment by toutils** [comment]
I haven't put it on the releases yet, I wanted to test it further first by doing a full scrape for the next database. The latest commit right now should be running fine, I think all the errors from the initial 0.3 commit I put up are taken care of. In the future I'm going to put the next version on a separate branch so it's not confusing when the readme on the frontpage doesn't apply to the latest, old, release.

**Comment by toutils** [comment]
0.3 is now on the release tab, which should run fine in windows 7.
