### ISSUE TITLE
TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by rtayne** [toutils/todbmanager#4]
python todbmanager.py -h
creating reviews table if needed...
creating reviews indexes if needed...
creating comments table if needed...
creating comments index if needed...
recreating hashes if needed...
Testing:False
Null Only:True
Traceback (most recent call last):
  File "todbmanager.py", line 817, in <module>
    main()
  File "todbmanager.py", line 657, in main
    db_rehash('to.db', TESTING=False, null_only=True)
  File "\todbmanager-0.2\db_rehash.py", line 95, in db_rehash
    comment_hash=str(hashlib.sha256(comment_hash_str).hexdigest())
TypeError: Unicode-objects must be encoded before hashing

**Comment by rtayne** [comment]
I was able to get past this error by doing a encode('utf-8') for any hashlib.sha256 object example:

comment_hash=str(hashlib.sha256(comment_hash_str.encode('utf-8')).hexdigest())
