### ISSUE TITLE
OSError: [WinError 87] The parameter is incorrect

### ISSUE THREAD

**Issue by rtayne** [toutils/todbmanager#6]
scrape_reports_page:PASS
===TO Database Manager===
1: Update Database
2: Database Stats
3: Delete Blocked Ids from Database
4: Delete Database
5: Download Database (Broken)
6: Run Tests
7: Export Database
q: Quit
select:1
Update Database
running self test...
scrape_reports_page:PASS
checking if logged in...
not logged in

sending login request...
login success!
config: enter for (default)
auto-update: will stop update when no new data on a page
auto-update (y)/n:
page start(1):
page end:0 = all pages (default)
page end(0):
rate limit(2.0) in seconds:
2019-03-07 13:43:05.765018:info:scrape_to:scrape started

scrape_to:auto updating page_end
scrape_to:auto update enabled
scarpe_to:setting orderby to edit
scraping pages:1-15084
rate limit,waiting:1.984645128250122
requesting:reports?page=1
launching process for:reports?page=1
Traceback (most recent call last):
  File "todbmanager.py", line 817, in <module>
    main()
  File "todbmanager.py", line 741, in main
    scrape_to(to_api,page_start,page_end,rate_limit,auto_update)
  File "todbmanager.py", line 467, in scrape_to
    scrape_process.start()
  File "C:\Users\User1\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot serialize '_io.BufferedReader' object
PS C:\Users\User1\Downloads\TO_DB\todbmanager-0.2\todbmanager-0.2> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User1\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\reduction.py", line 82, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] The parameter is incorrect

**Comment by toutils** [comment]
This is from 0.2. Try downloading the latest commit which is currently https://github.com/toutils/todbmanager/commit/9b1542903fbb6dd2839799fde06e7f6b035d3f19
unless there's any bugs this is what 0.3 is going to be, I'll update the releases as soon as the new database is done, sometime today.

**Comment by toutils** [comment]
0.3 is now on the release tab, which should run fine in windows 7.
